# default config for ddpg
name: DDPG

# cnn or lstm or gru
network_type: gru

# log_return, simple_return, diff_sharpe_ratio, diff_sortino_ratio
reward_type: diff_sharpe_ratio

num_episodes: 100
warmup_steps: 500
eval_steps: 1
batch_size: 64
tau: 0.001
gamma: 0.99
buffer_size: 10000
lr_actor: 0.0001
lr_critic: 0.001
