# default config for ddpg
name: DDPG

# cnn / lstm / gru / cnn_gru
network_type: lstm

# log_return, simple_return, diff_sharpe_ratio, diff_sortino_ratio
reward_type: log_return

num_episodes: 100
warmup_steps: 500
eval_steps: 1
batch_size: 64
tau: 0.001
gamma: 0.99
buffer_size: 10000
lr_actor: 0.0001
lr_critic: 0.001
