# default config for sac
name: SAC

checkpoint_folder: checkpoints_sac

# cnn or lstm
network_type: lstm 

num_episodes: 100
eval_steps: 10
batch_size: 64
tau: 0.005
gamma: 0.99
reward_scale: 20
buffer_size: 10000
lr_actor: 0.00001
lr_critic: 0.001

alpha_tuning: False
alpha: 0.2 # use this if alpha_tuning is False
lr_alpha: 0.0001 # use this if alpha_tuning is True
